//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FuelConsumption
    {
        public int Id { get; set; }
        public int vehicle_id { get; set; }
        public double volume { get; set; }
        public double price { get; set; }
        public Nullable<System.DateTime> date_consoommation { get; set; }
        public double mileage { get; set; }
    
        public virtual Vehicle Vehicle { get; set; }
    }
}
