//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rest
    {
        public int Id { get; set; }
        public int worker_id { get; set; }
        public Nullable<System.DateTime> date_rest { get; set; }
        public string description { get; set; }
    
        public virtual Worker Worker { get; set; }
    }
}
